clone_folder: c:\dev\glm-cmake

os:
  - Visual Studio 2013
  - Visual Studio 2013
  - Visual Studio 2017

platform:
  - x86_64

build_script:
- cmake --version
- md build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON ..
- cmake -E time cmake --build . 
