clone_folder: c:\dev\glm-cmake

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_AVX2=ON'
      CONFIGURATION: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_AVX2=ON'
      CONFIGURATION: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_FORCE_PURE=ON'
      CONFIGURATION: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_FORCE_PURE=ON'
      CONFIGURATION: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 14 2015 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_AVX=ON'
      CONFIGURATION: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 14 2015 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_AVX=ON'
      CONFIGURATION: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 14 2015 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_FORCE_PURE=ON'
      CONFIGURATION: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 14 2015 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_FORCE_PURE=ON'
      CONFIGURATION: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: 'Visual Studio 12 2013 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_SSE2=ON'
      CONFIGURATION: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: 'Visual Studio 12 2013 Win64'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_FORCE_PURE=ON'
      CONFIGURATION: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: 'Visual Studio 12 2015'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON -DGLM_TEST_ENABLE_SIMD_SSE2=ON'
      CONFIGURATION: Release

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_GENERATOR: 'Visual Studio 12 2015'
      ADDITIONAL_CMAKE_ARGS: '-DGLM_TEST_ENABLE=ON -DGLM_TEST_FORCE_PURE=ON'
      CONFIGURATION: Release

platform:
  - x64

build:
  parallel: true
  verbosity: minimal

before_build:
- cmake --version
- md build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER $ADDITIONAL_CMAKE_ARGS ..

build_script:
- cmake -E time cmake --build . --config %CONFIGURATION% -- /verbosity:minimal

after_build:
- ctest -C %CONFIGURATION%
