clone_folder: c:\dev\glm-cmake

os:
  - Visual Studio 2013
  - Visual Studio 2013
  - Visual Studio 2017

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

platform:
  - x86
  - x86_64

build:
  parallel: true
  verbosity: minimal

build_script:
- cmake --version
- md build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_LANG_EXTENSIONS=ON ..
- cmake -E time cmake --build . --config %CONFIGURATION%

after_build:
- ctest -C %CONFIGURATION%
