language: cpp

os:
  - linux
  - osx

compiler:
  - g++
  - clang

before_script: 
- mkdir ./build
- cd ./build
- cmake -DGLM_TEST_ENABLE=ON -DGLM_TEST_ENABLE_CXX_98=ON ..

script:
  - cmake --build .
  - ctest
